name: Microservices

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  Microservices-Build:
    runs-on: ubuntu-latest
    steps:
     - name: 🛒 Checkout
       uses: actions/checkout@v3
       with:
        fetch-depth: 0

     - name: Set Up Golang
       uses: actions/setup-go@v3
       with:
        go-version: '^1.18' # The Go version to download (if necessary) and use.
     - run: go version

     - name: Installing Docker Compose 
       run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
     - name: 🛠️ Build
       run: |
        ls -la
        cd project
        make up_build

        echo "LS IN PROJECT DIRECTORY" 
        ls -la

     - name: Removing the db-data directory 
       run: |
        sudo rm -r project/db-data
        ls -la project

     - name: ⬆️ Uploading artifact
       uses: actions/upload-artifact@v3
       with: 
        name: my-artifact
        path: .


  Deploying:
   runs-on: ubuntu-latest
   if: github.event_name == 'push'
   needs: Microservices-Build
   env:
     broker-service: dev-anibal
   steps:
    - name: ⬇️ Downloading artifact
      uses: actions/download-artifact@v3
      with:
       name: my-artifact
     
    
    - name: Display structure of downloaded files
      run: ls -la


    - name: Deploying to GCR
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.broker-service }}
        export_default_credentials: true
    - name: Configure Docker Client
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

    - name: Change directory to broker-service
      run: |
        cd broker-service
        ls -la
    - name: Build the Broker Service Docker image 🧙🏼‍♂️
      run: |
        docker build -f broker-service/broker-service.dockerfile -t  broker:latest .
        echo "LS supposdley in the broker service directory"
        ls -la
    
    - name: Push the Broker Service Docker Image to Container Registry (GCR) 🧙🏼‍♂️⬆️
      run: |
       docker tag broker:latest gcr.io/broker-service/broker:latest
       docker tag broker:latest gcr.io/broker-service/broker:${{ steps.date.outputs.date }}
       docker push gcr.io/broker-service/broker:latest
       docker push gcr.io/broker-service/broker:${{ steps.date.outputs.date }}