name: Microservices

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  Microservices-Build:
    runs-on: ubuntu-latest
    steps:
     - name: 🛒 Checkout
       uses: actions/checkout@v3
       with:
        submodules: true
        fetch-depth: 0

     - name: Make Update 🧐
       run: |
        make update  
                
     - name: 🛠️ Build
       run: |
        make up_build

     - name: ⬆️ Uploading artifact
       uses: actions/upload-artifact@v3
       with: 
        name: my-artifact
        path: .


  # Deploying:
  #  runs-on: ubuntu-latest
  #  if: github.event_name == 'push'
  #  needs: hugo
  #  env:
    #  IMAGE_NAME: week9
    #  PROJECT_ID: anibal-week9
  #  steps:
    # - name: ⬇️ Downloading artifact
      # uses: actions/download-artifact@v3
      # with:
      #  name: my-artifact
    #  
    # 
    # - name: Display structure of downloaded files
      # run: ls -la
# 
# 
    # - name: Deploying to GCR
      # uses: google-github-actions/setup-gcloud@v0
      # with:
        # service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        # project_id: ${{ env.PROJECT_ID }}
        # export_default_credentials: true
# 
      # 
    # - name: Get current date # get the date of the build
      # id: date
      # run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
# 
    # 
    # - name: Build the Docker image 
      # run: |
        # docker build . --file Dockerfile --tag  $IMAGE_NAME:latest
    # - name: Configure Docker Client
      # run: |
      #  gcloud auth configure-docker --quiet
      #  gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    # 
    # - name: Push Docker Image to Container Registry (GCR)
      # run: |
      #  docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
      #  docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ steps.date.outputs.date }}
      #  docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
      #  docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ steps.date.outputs.date }}